name = "rec-time-fe"
compatibility_date = "2024-09-01"
account_id = "a6d1a427beffc5898641e90e99cdb49b"  # ✅ Ellan122316 계정 ID로 변경

[build]
command = "npm run build"

# Pages 배포 설정
pages_build_output_dir = "build/client"
